# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.4.1
# Orchestrate or schedule a set of jobs

jobs:
  print_hello:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: Hello Printer
          command: |
            echo 'Hello'
            echo 'Is it me you are looking for?'

  print_world:
    docker:
      - image: alpine:3.7
    steps:
      - run:
          name: World Printer
          command: |
            echo 'World'
            echo 'You still there?'
      - run:
          name: World Replier
          command: |
            echo 'Yup, still here'

workflows:
  # Name the workflow "welcome"
  welcome:
    # Run the jobs in their own containers
    jobs:
      - print_hello
      - print_world
          requires:
            - print_hello
